module.exports = function(param){
    const menu = [];
    var data = new Object();
    data.id = 1;
    data.type = 'main';
    data.menu = 'หน้าแรก';
    data.path = '';
    data.icon = '';
    data.attr = '';
    menu.push(data);
    data = new Object();
    data.id = 2;
    data.type = 'list';
    data.menu = 'Home';
    data.path = '/';
    data.icon = 'assessment';
    data.attr = '';

    menu.push(data);
    data = new Object();
    data.id = 3;
    data.type = 'main';
    data.menu = 'เมนู';
    data.path = '';
    data.attr = '';
    data.icon = '';
    menu.push(data);
    data = new Object();
    data.id = 4;
    data.type = 'list';
    data.menu = 'จัดการ';
    data.path = '.setting';
    data.icon = 'insert_drive_file';
    data.attr = 'data-toggle=collapse role=button aria-expanded=false aria-controls='+data.path;
    menu.push(data);
    data = new Object();
    data.id = 5;
    data.type = 'list';
    data.menu = 'ผู้ใช้งาน';
    data.path = '/user';
    data.icon = 'assignment_ind';
    data.attr = '';
    data.child_id = 'setting';
    menu.push(data);
    data = new Object();
    data.id = 6;
    data.type = 'list';
    data.menu = 'ผู้ป่วย';
    data.path = '/patient';
    data.icon = 'people';
    data.attr = '';
    data.child_id = 'setting';
    menu.push(data);
    data = new Object();
    data.id = 7;
    data.type = 'main';
    data.menu = 'รายงาน';
    data.path = '';
    data.attr = '';
    data.icon = '';
    menu.push(data);
    data = new Object();
    data.id = 8;
    data.type = 'list';
    data.menu = 'รายงานผู้ป่วย';
    data.path = '/report_patient';
    data.icon = 'description';
    data.attr = '';
    data.child_id = '';
    menu.push(data);
    data = new Object();
    data.id = 9;
    data.type = 'list';
    data.menu = 'ข้อมูล';
    data.path = '/assetp1';
    data.icon = 'description';
    data.attr = '';
    data.child_id = '';
    menu.push(data);
    return menu;

}
